### ISSUE TITLE
High CPU usage when using your node

### ISSUE THREAD

**Issue by sniicker** [bartbutenaers/node-red-contrib-cpu#1]
Hi,

when i use your node on my system i have a really high cpu usage.
see here
![Unbenannt](https://user-images.githubusercontent.com/67097444/147793732-f4a87f0d-62e1-4128-b133-898bbd7e0083.JPG)

After Deploy the cpu usage goes up to nearly 100% with a trigger every 5 seconds.
When i trigger every 30sec it looks like this

![Unbenannt2](https://user-images.githubusercontent.com/67097444/147793774-c04efbac-8f0b-4345-a11f-549596e9fa34.JPG)
 
Is this a normal behavior? Or can you help me?
Im on win10 with 
Node JS V14.18.2 
NPM 8.3.0 
NR 2.1.4

Thanks & nice Greetings

**Comment by bartbutenaers** [comment]
Hi @sniicker,
Do you mean that every time you trigger the cpu node, that my cpu node consumes so much cpu?
Never looked at the cpu usage of my cpu node to be honest...
Bart

**Comment by sniicker** [comment]
Yes exactly, i only activated and deactivated your node, all other flwos and nodes were not changed.

**Comment by bartbutenaers** [comment]
So weird this has never been reported before...  Will have a look after new year.  Enjoy yor evening!!

**Comment by bartbutenaers** [comment]
@sniicker,

I can barely see the spikes caused by my node, on a Windows 10 portable:

![image](https://user-images.githubusercontent.com/14224149/147852144-82411ce7-780d-444a-b909-91fcca9f9722.png)

Only when I activate the *"Send a single message with core temperature(s)"* checkbox, the peaks go to about 25%.
1. Can you share a screenshot of your node's config screen please.  
2. And can you let me know what happens when the output of your cpu node is not wired to other nodes (if that wouldn't be the case yet)?  Because when I wire my output to a chart node, then indeed cpu usage starts increasing a lot (for a measurement every minute)...

**Comment by sniicker** [comment]
Hi @bartbutenaers ,
thx for your fast response. I think your peaks are less because your system is more powerful than mine.

Normaly i have all boxes checked. After your "temperature" discovery i tried a few things.
If i check the first 3 boxes, i can trigger as often i can, the cpu even will not notice anything.
If i uncheck the first 3 and only check the "temperature" one the cpu peak goes up to 100%. Maybe bevause the node cannot get a temperature value, i only get null back. 
![image](https://user-images.githubusercontent.com/67097444/147853532-39824ac9-78af-4d47-96b7-73e61f739144.png)

For me it will be ok, i can use your node without the temperature feature, but maybe there is something wrong with error handling ? I dont know, just thinkin.

**Comment by bartbutenaers** [comment]
Hi @sniicker,
My best wishes!!

> maybe there is something wrong with error handling ? I dont know, just thinkin.

Yes indeed you might be correct.  On the other side, if you look at the [issues](https://github.com/sebhildebrandt/systeminformation/issues) of the systeminformation library - that I only use for the cpu temperature - there are also users reporting 100% cpu on Windows....
So not sure what is going on.
I see in my debugger that I don't get any temperature info anymore from that library:

![image](https://user-images.githubusercontent.com/14224149/148340636-96d11b5e-17e4-4bfa-ab83-b57682832bdd.png)

Which is weird because nobody seems to have reported that yet.  It is a pitty that the NodeJs [os](https://nodejs.org/api/os.html) module doesn't support temperatures out of the box, because the systeminformation library is quite big and I only need it to get the temperature...

> Maybe bevause the node cannot get a temperature value, i only get null back.

I developed a couple of days ago the [node-red-contrib-v8-cpu-profiler/blob/main/README.md](https://github.com/bartbutenaers/node-red-contrib-v8-cpu-profiler/blob/main/README.md) library.  I you should have some time, we could try to use that one to figure out what is going on on your side.  These are the steps:
1. Install that node from my github repo (because not on npm yet) via this command from within your .node-red folder:
   ```
   npm install bartbutenaers/node-red-contrib-v8-cpu-profiler
   ```
2. Import the example flow from my readme page.
3. Press the button of the "Start profiling" inject node.
4. Share the generated xxx.cpuprofile file with me here.

Then I will have a look at that cpu profile if you like.  Perhaps I cannot get enough information from it, but then we at least have tried...

**Comment by sniicker** [comment]
Hi @bartbutenaers ,

i tried, but failed to install your node...

> 0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'bartbutenaers/node-red-contrib-v8-cpu-profiler'
0 verbose cli ]
1 info using npm@8.3.0
2 info using node@v14.18.2
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:C:\Users\***\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 18ms
6 timing config:load:builtin Completed in 20ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\***\.node-red\.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:C:\Users\***\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\***\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 51ms
19 timing npm:load:configload Completed in 51ms
20 timing npm:load:setTitle Completed in 3ms
21 timing config:load:flatten Completed in 13ms
22 timing npm:load:display Completed in 18ms
23 verbose logfile C:\Users\***\AppData\Local\npm-cache\_logs\2022-01-10T11_29_31_584Z-debug-0.log
24 timing npm:load:logFile Completed in 25ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 102ms
28 timing arborist:ctor Completed in 3ms
29 timing idealTree:init Completed in 2438ms
30 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
31 timing idealTree Completed in 2519ms
32 timing command:install Completed in 2567ms
33 verbose stack Error: An unknown git error occurred
33 verbose stack     at makeError (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
33 verbose stack     at C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:36:26
33 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
34 verbose cwd C:\Users\***\.node-red
35 verbose Windows_NT 10.0.19044
36 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bartbutenaers/node-red-contrib-v8-cpu-profiler"
37 verbose node v14.18.2
38 verbose npm  v8.3.0
39 error code ENOENT
40 error syscall spawn git
41 error path git
42 error errno -4058
43 error enoent An unknown git error occurred
44 error enoent This is related to npm not being able to find a file.
44 error enoent
45 verbose exit -4058
46 timing npm Completed in 4218ms
47 verbose unfinished npm timer reify 1641814173220
48 verbose unfinished npm timer reify:loadTrees 1641814173253
49 verbose unfinished npm timer idealTree:userRequests 1641814175696
50 verbose code -4058
51 error A complete log of this run can be found in:
51 error     C:\Users\***\AppData\Local\npm-cache\_logs\2022-01-10T11_29_31_584Z-debug-0.log


Do you know something about it? Can you help me?

**Comment by sniicker** [comment]
On the otherside i found a useful tool but im not so experienced to use it. Mybe you can use it.

[https://openhardwaremonitor.org/documentation/](url)

The Software publishes all sensor data to WMI. I already could read the data but till now i found no way to read it wihtin NR.  
Maybe it can help you?!

**Comment by bartbutenaers** [comment]
Hi @sniicker,
I think you have not installed git.  But the ***node-red-contrib-v8-cpu-profiler***  node is now also available in the palette, so you can install it now via your 'Manage palette' menu in the flow editor.  You should just need to change the file path in the last node of the example flow.

**Comment by sniicker** [comment]
Hi @bartbutenaers,

i also failed via Palette Manager.

> 2022-01-11T08:11:44.750Z Installieren : node-red-contrib-v8-cpu-profiler 1.0.0
2022-01-11T08:11:44.767Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-v8-cpu-profiler@1.0.0
2022-01-11T08:12:04.742Z [err] npm
2022-01-11T08:12:04.742Z [err]  WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-01-11T08:12:20.734Z [out] 
2022-01-11T08:12:20.734Z [out] > v8-profiler-next@1.5.1 install C:\Users\***\.node-red\node_modules\v8-profiler-next
2022-01-11T08:12:20.734Z [out] > node-gyp rebuild
2022-01-11T08:12:20.734Z [out] 
2022-01-11T08:12:20.792Z [out] 
2022-01-11T08:12:20.792Z [out] C:\Users\***\.node-red\node_modules\v8-profiler-next>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
2022-01-11T08:12:21.623Z [err] gyp
2022-01-11T08:12:21.624Z [err]  ERR! 
2022-01-11T08:12:21.624Z [err] find Python 
2022-01-11T08:12:21.624Z [err] gyp ERR!
2022-01-11T08:12:21.624Z [err]  find Python Python is not set from command line or npm configuration
2022-01-11T08:12:21.624Z [err] gyp
2022-01-11T08:12:21.624Z [err]  ERR! find Python Python is not set from environment variable PYTHON
2022-01-11T08:12:21.624Z [err] gyp
2022-01-11T08:12:21.624Z [err]  ERR! find Python
2022-01-11T08:12:21.624Z [err]  checking if "python" can be used
2022-01-11T08:12:21.624Z [err] gyp
2022-01-11T08:12:21.624Z [err]  ERR! find Python - "python" is not in PATH or produced an error
2022-01-11T08:12:21.625Z [err] gyp ERR! find Python checking if "python2" can be used
2022-01-11T08:12:21.625Z [err] gyp ERR!
2022-01-11T08:12:21.625Z [err]  find Python - "python2" is not in PATH or produced an error
2022-01-11T08:12:21.625Z [err] gyp ERR!
2022-01-11T08:12:21.625Z [err]  find Python checking if "python3" can be used
2022-01-11T08:12:21.625Z [err] gyp ERR! 
2022-01-11T08:12:21.625Z [err] find Python - "python3" is not in PATH or produced an error
2022-01-11T08:12:21.625Z [err] gyp ERR!
2022-01-11T08:12:21.625Z [err]  find Python checking if the py launcher can be used to find Python 2
2022-01-11T08:12:21.625Z [err] gyp
2022-01-11T08:12:21.625Z [err]  ERR! find Python - "py.exe" is not in PATH or produced an error
2022-01-11T08:12:21.625Z [err] gyp ERR! 
2022-01-11T08:12:21.625Z [err] find Python checking if Python is C:\Python27\python.exe
2022-01-11T08:12:21.625Z [err] gyp ERR!
2022-01-11T08:12:21.625Z [err]  find Python - "C:\Python27\python.exe" could not be run
2022-01-11T08:12:21.625Z [err] gyp
2022-01-11T08:12:21.625Z [err]  ERR! find Python checking if Python is C:\Python37\python.exe
2022-01-11T08:12:21.626Z [err] gyp ERR! 
2022-01-11T08:12:21.626Z [err] find Python - "C:\Python37\python.exe" could not be run
2022-01-11T08:12:21.626Z [err] gyp 
2022-01-11T08:12:21.626Z [err] ERR! find Python
2022-01-11T08:12:21.626Z [err]  
2022-01-11T08:12:21.626Z [err] gyp ERR! 
2022-01-11T08:12:21.626Z [err] find Python **********************************************************
2022-01-11T08:12:21.626Z [err] gyp ERR!
2022-01-11T08:12:21.626Z [err]  find Python You need to install the latest version of Python.
2022-01-11T08:12:21.626Z [err] gyp
2022-01-11T08:12:21.626Z [err]  ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-01-11T08:12:21.626Z [err] gyp ERR! 
2022-01-11T08:12:21.626Z [err] find Python you can try one of the following options:
2022-01-11T08:12:21.626Z [err] gyp 
2022-01-11T08:12:21.626Z [err] ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
2022-01-11T08:12:21.626Z [err] gyp ERR! find Python
2022-01-11T08:12:21.626Z [err]    (accepted by both node-gyp and npm)
2022-01-11T08:12:21.626Z [err] gyp ERR!
2022-01-11T08:12:21.626Z [err]  find Python - Set the environment variable PYTHON
2022-01-11T08:12:21.626Z [err] gyp
2022-01-11T08:12:21.627Z [err]  ERR! find Python - Set the npm configuration variable python:
2022-01-11T08:12:21.627Z [err] gyp ERR! 
2022-01-11T08:12:21.627Z [err] find Python   npm config set python "C:\Path\To\python.exe"
2022-01-11T08:12:21.627Z [err] gyp 
2022-01-11T08:12:21.627Z [err] ERR! find Python For more information consult the documentation at:
2022-01-11T08:12:21.627Z [err] gyp 
2022-01-11T08:12:21.627Z [err] ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-01-11T08:12:21.628Z [err] gyp ERR! find Python **********************************************************
2022-01-11T08:12:21.628Z [err] gyp ERR! find Python 
2022-01-11T08:12:21.629Z [err] gyp
2022-01-11T08:12:21.629Z [err]  ERR! configure error 
2022-01-11T08:12:21.630Z [err] gyp ERR! 
2022-01-11T08:12:21.630Z [err] stack Error: Could not find any Python installation to use
2022-01-11T08:12:21.630Z [err] gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
2022-01-11T08:12:21.630Z [err] gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
2022-01-11T08:12:21.630Z [err] gyp
2022-01-11T08:12:21.630Z [err]  ERR!
2022-01-11T08:12:21.630Z [err]  stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
2022-01-11T08:12:21.630Z [err] gyp
2022-01-11T08:12:21.630Z [err]  ERR! stack
2022-01-11T08:12:21.630Z [err]      at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
2022-01-11T08:12:21.630Z [err] gyp ERR!
2022-01-11T08:12:21.630Z [err]  stack     at exithandler (child_process.js:390:5)
2022-01-11T08:12:21.630Z [err] gyp 
2022-01-11T08:12:21.630Z [err] ERR! stack
2022-01-11T08:12:21.631Z [err]      at ChildProcess.errorhandler (child_process.js:402:5)
2022-01-11T08:12:21.631Z [err] gyp
2022-01-11T08:12:21.631Z [err]  ERR! stack
2022-01-11T08:12:21.631Z [err]      at ChildProcess.emit (events.js:400:28)
2022-01-11T08:12:21.631Z [err] gyp ERR! 
2022-01-11T08:12:21.631Z [err] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
2022-01-11T08:12:21.631Z [err] gyp ERR!
2022-01-11T08:12:21.631Z [err]  stack     at onErrorNT (internal/child_process.js:469:16)
2022-01-11T08:12:21.631Z [err] gyp
2022-01-11T08:12:21.631Z [err]  ERR! stack
2022-01-11T08:12:21.631Z [err]      at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-01-11T08:12:21.632Z [err] gyp
2022-01-11T08:12:21.632Z [err]  ERR! System Windows_NT 10.0.19044
2022-01-11T08:12:21.632Z [err] gyp 
2022-01-11T08:12:21.632Z [err] ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
2022-01-11T08:12:21.632Z [err] gyp ERR!
2022-01-11T08:12:21.632Z [err]  cwd C:\Users\***\.node-red\node_modules\v8-profiler-next
2022-01-11T08:12:21.632Z [err] gyp ERR! 
2022-01-11T08:12:21.632Z [err] node -v v14.18.2
2022-01-11T08:12:21.632Z [err] gyp 
2022-01-11T08:12:21.632Z [err] ERR! node-gyp -v v5.1.0
2022-01-11T08:12:21.632Z [err] gyp ERR!
2022-01-11T08:12:21.632Z [err]  not ok 
2022-01-11T08:12:23.317Z [err] npm WARN
2022-01-11T08:12:23.318Z [err]  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
2022-01-11T08:12:23.318Z [err] npm WARN 
2022-01-11T08:12:23.318Z [err] notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2022-01-11T08:12:23.319Z [err] 
2022-01-11T08:12:23.366Z [err] npm ERR! 
2022-01-11T08:12:23.366Z [err] code ELIFECYCLE
2022-01-11T08:12:23.366Z [err] npm ERR! errno 1
2022-01-11T08:12:23.395Z [err] npm ERR! v8-profiler-next@1.5.1 install: `node-gyp rebuild`
2022-01-11T08:12:23.395Z [err] npm ERR! Exit status 1
2022-01-11T08:12:23.395Z [err] npm ERR!
2022-01-11T08:12:23.395Z [err]  
2022-01-11T08:12:23.395Z [err] npm ERR! Failed at the v8-profiler-next@1.5.1 install script.
2022-01-11T08:12:23.395Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-11T08:12:23.412Z [err] 
2022-01-11T08:12:23.412Z [err] npm
2022-01-11T08:12:23.412Z [err]  ERR! A complete log of this run can be found in:
2022-01-11T08:12:23.412Z [err] npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2022-01-11T08_12_23_399Z-debug.log
2022-01-11T08:12:23.456Z rc=1

**Comment by bartbutenaers** [comment]
Evening @sniicker,

> "python" is not in PATH or produced an error

Seems Python needs to be installed, in order to run this node.  I wasn't aware of that, since I had already installed Python (2.7).
You can decide yourself whether you want to continue with the installation.  Because I can imagine that this might be far away from your comfort zone?  But if you want to proceed, don't hesitate to ask help here...

**Comment by sniicker** [comment]
Hi @bartbutenaers ,
The comfort zone shrinks with every challenge. Most of the time I get everything working.  ;)

python was installed but not as path, but i also needed Visual Studio Tools like mentioned here
[https://github.com/nodejs/node-gyp#on-windows](url)

1.Profile without Trigger
2.Profile with 2 Triggers at begining and middle
3.Profile with Trigger every Second
[CPU_profile.zip](https://github.com/bartbutenaers/node-red-contrib-cpu/files/7854528/CPU_profile.zip)

**Comment by bartbutenaers** [comment]
Evening @sniicker,
Starting to interpret the Chrome Developer Tools profilier output, is a challenge for me also ...
Thanks for taking the time to install this!  It gives me insights in how people experience/use my nodes.

I have opened your profiles in Chrome Developer tools (as described [here](https://github.com/bartbutenaers/node-red-contrib-v8-cpu-profiler/wiki/Do-a-Node-RED-CPU-profiling-analysis-via-Chrome-Developer-Tools)):

![image](https://user-images.githubusercontent.com/14224149/149236290-93379298-020d-4572-a2d5-5a8931614b08.png)

1. For example I load your profile with a trigger every second, in order to be able to see the repetitive pattern (of cpu peaks every second as you can see in the chart above).

2. Then I zoom in on one of the cpu peaks.

3. In the method hotspots I see that most of the cpu time is being spent in the os.cpus()

4. That function is part of [this](https://nodejs.org/api/os.html#oscpus) NodeJs module.  So that is not code of mine that I can optimize.

5. But I call that function quite a number of times in a loop:

   ![image](https://user-images.githubusercontent.com/14224149/149236885-f24282af-84bc-447f-9cd2-20b958acd1cf.png)

   I had expected that the Google's V8 Javascript engine would have detected this, and optimized the code to call it only once.  But perhaps it doesn't that.  I will create a fix to call that function once, and then loop the cached result.  Hopefully that lowers the cpu peaks for you.  Will let you know when I have a fix version to test...

BTW you can see some similar results (over the entire timeline) in the *"Heavy (bottom up)"* table:

![image](https://user-images.githubusercontent.com/14224149/149237612-f90dde49-c632-47ad-b603-27ab35fc68b2.png)

Did you capture these cpu profiles while your ***"... core temperatures"*** checkbox (in the cpu node) was activated?  Because then I would have expected other (temperature related) methods to popup in the method hotspots.  It looks to me like that checkbox was deactivated during these tests??

**Comment by sniicker** [comment]
Good Morning @bartbutenaers,

i have to say sorry. I had another flow with a running cpu node, but the temperatures were definitly checked.
So i made 2 new profiles only with one node in the whole projekt.
In the video you can see the first run without temperatures and cpu doesnt even notice. 
Second profile with temperatuers and as soon as i start the trigger, the cpu goes up to 100%.
In de profiles i cannot really see a big differenze but maybe you can find something interessting.
[with&withoutTemp.zip](https://github.com/bartbutenaers/node-red-contrib-cpu/files/7860965/with.withoutTemp.zip)

Have a nice day.

**Comment by bartbutenaers** [comment]
Hmm you are right.  By looking at the profile graphs, I don't see any issues at all.  Very weird.  Seems we are both back at school here...

The movie is very illuminating!  Otherwise I have to guess what you are seeing...

Don't know if you have seen another recent node of mine: [node-red-contrib-process-resources](https://github.com/bartbutenaers/node-red-contrib-process-resources).  It shows only the cpu of the Node-RED related processes.  That might also perhaps be useful to troubleshoot something like this.  It should reveal whether your cpu usage is caused by NOde-RED or not...

**Comment by bartbutenaers** [comment]
> I had expected that the Google's V8 Javascript engine would have detected this, and optimized the code to call it only once. But perhaps it doesn't that. I will create a fix to call that function once, and then loop the cached result. Hopefully that lowers the cpu peaks for you. Will let you know when I have a fix version to test...

I have implemented this performance fix in a new "performance_fix" branch of my Github repository.  You can install that branch with following command (which needs to be executed within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-cpu#performance_fix
```
Would be nice if you could test whether this helps anything (when not using temperature).
P.S. you need to have git installed to be able to execute the above command...

**Comment by sniicker** [comment]
Hi @bartbutenaers 

i tried your fix and i can see improvement in the profile but my cpu still is going up to 100%
[perfomanceFIX_1642411763499-1642411783120.zip](https://github.com/bartbutenaers/node-red-contrib-cpu/files/7880861/perfomanceFIX_1642411763499-1642411783120.zip)


I also tried your resources node, but cannot see anything interesting. If i start triggering every sec. the charts are not changing. And the peaks may come from other things.. 
![image](https://user-images.githubusercontent.com/67097444/149747463-2442da39-ba5c-4cff-87a6-bdcabfcde44d.png)

**Comment by bartbutenaers** [comment]
What a pitty that the fix didn't help...

I can't conclude anything from the cpu profile.   The weird thing is that you get a ***very deep*** call stack containing only ExpressJs stuff:

![image](https://user-images.githubusercontent.com/14224149/149839836-13931b12-7d45-4305-83cc-7fc32368c3ce.png)

Express js is the NodeJs webserver.  My CPU node is pure backend stuff, which means I don't do any data communication between the backend server and the frontend (flow editor).  So I can only explain those peaks if they are triggered by another node, most probably somehow related with the cpu node...

Is the output of your CPU node wired to other nodes?  If so, could you remove all wires at the output and test again please.

Had another [issue](https://github.com/bartbutenaers/node-red-contrib-cpu/issues/2#issuecomment-1013712513) few days ago, and he had a debug node at the output with the "_system console_" option activated...

**Comment by sniicker** [comment]
Morning @bartbutenaers 

I think the fix did not work, because the problem comes not from the cpu side (code you posted above).
The CPU only goes up if i activate the "temperatures". So the Problem will be there.
As you wrote above, you just use the the systeminformation library and i think you cannot do any more, excpect to check sometimes the library and look if they fixed it. 

My output of the node is not connected ...
